services:
  - type: web
    name: sama-club
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sama_club.settings

