services:
  - type: web
    name: sama_club
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sama_club.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sama_club.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: sama_club.onrender.com
