# Generated by Django 5.2.4 on 2025-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversaire', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('score_equipe', models.PositiveIntegerField(blank=True, null=True)),
                ('score_adversaire', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
